runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  secure: always

- url: /arcake/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: arcake/\1
  upload: arcake/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /blitblort-demo/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: blitblort-demo/\1
  upload: blitblort-demo/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /blow-up/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: blow-up/\1
  upload: blow-up/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /c3d/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: c3d/\1
  upload: c3d/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /combust-a-move/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: combust-a-move/\1
  upload: combust-a-move/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /greyfield/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: greyfield/\1
  upload: greyfield/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /lost-on-mars/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3|datagz|memgz|jsgz))$
  static_files: lost-on-mars/\1
  upload: lost-on-mars/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3|datagz|memgz|jsgz)$
  secure: always

- url: /markovio/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: markovio/\1
  upload: markovio/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /opdozitz/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: opdozitz/\1
  upload: opdozitz/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always
  
- url: /pipevo/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3|slur))$
  static_files: pipevo/\1
  upload: pipevo/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3|slur)$
  secure: always

- url: /scrace/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: scrace/\1
  upload: scrace/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /tapwords/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: tapwords/\1
  upload: tapwords/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /tojam11/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: tojam11/\1
  upload: tojam11/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /tojam12/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: tojam12/\1
  upload: tojam12/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /tojam13/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: tojam13/\1
  upload: tojam13/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /wavebreaker/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3))$
  static_files: wavebreaker/\1
  upload: wavebreaker/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3)$
  secure: always

- url: /wordevo/(.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3|txt))$
  static_files: wordevo/\1
  upload: wordevo/.*\.(png|jpg|svg|html|css|js|json|ogg|wav|mp3|txt)$
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- .*\.xcf
- .*\.aup
- .*\.md
- .*\.java
- .*\.py
- .*/LICENSE
- \.git
