application: ponderous-mad
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  secure: always

- url: /scrace
  static_dir: scrace
  secure: always

- url: /opdozitz
  static_dir: opdozitz
  secure: always
  
- url: /spoonful
  static_dir: spoonful
  secure: always
  
- url: /specialtivity
  static_dir: specialtivity
  secure: always
  
- url: /blow-up
  static_dir: blow-up
  secure: always
  
- url: /blitblort
  static_dir: blitblort
  secure: always
  
- url: /combust-a-move
  static_dir: combust-a-move
  secure: always
  
- url: /c3d
  static_dir: c3d
  secure: always

- url: /markovio
  static_dir: markovio
  secure: always
  
- url: /pipevo
  static_dir: pipevo
  secure: always
  
- url: /wordevo
  static_dir: wordevo
  secure: always

- url: /tapwords
  static_dir: tapwords
  secure: always
  
- url: /tojam11
  static_dir: tojam11
  secure: always
  
- url: /lost-on-mars
  static_dir: lost-on-mars
  secure: always
  
- url: /css
  static_dir: css
  secure: always
  
- url: /images
  static_dir: images
  secure: always

- url: /.*
  script: _go_app
  secure: always
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- .*\.xcf
- .*\.aup
- .*\.md
- .*\.java
- \.git
