application: ponderous-mad
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  secure: always

- url: /scrace
  static_dir: scrace
  secure: always

- url: /opdozitz
  static_dir: opdozitz
  secure: always
  
- url: /spoonful
  static_dir: spoonful
  secure: always
  
- url: /blow-up
  static_dir: blow-up
  secure: always
  
- url: /combust-a-move
  static_dir: combust-a-move
  secure: always
  
- url: /markovio
  static_dir: markovio
  secure: always
  
- url: /pipevo
  static_dir: pipevo
  secure: always
  
- url: /wordevo
  static_dir: wordevo
  secure: always

- url: /.*
  script: _go_app
  secure: always
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- .*\.xcf
- .*\.aup
- .*\.md
- .*\.java
- \.git
