application: ponderous-mad
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /clearpath
  static_dir: clearpath

- url: /scrace
  static_dir: scrace

- url: /opdozitz
  static_dir: opdozitz
  
- url: /spoonful
  static_dir: spoonful
  
- url: /markovio
  static_dir: markovio

- url: /.*
  script: _go_app
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- .*\.xcf
- .*\.aup
- .*\.md
- \.git
